# Generated by Django 3.1.5 on 2021-02-05 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peoples_budget', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetsubmission',
            name='submitter_address',
        ),
    ]
