# Generated by Django 3.1.5 on 2021-02-05 19:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('peoples_budget', '0002_remove_budgetsubmission_submitter_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetsubmission',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
